# Generated by Django 4.2.3 on 2023-07-13 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_tattos')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('LIMPOS', 'Limpos'), ('COBERTURAS', 'Coberturas'), ('FINEART', 'Fine Art'), ('OUTROS', 'Outros')], max_length=15)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
